name: Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  HelloWorld:
    runs-on: ubtuntu-latest

    steps:
    - name: Just hello world
      run: echo HelloWorld
