name: Deploy Runner

on:
  workflow_call

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose Build
        run: |
          docker compose -f docker-compose-global-build.yaml up -d

      - name: Owasp Zap
        run: |
          docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:23000